services:
    pixelx-php-app-1x:
        container_name: pixelx-php-app-1x
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8320:8320