services:
    php-app:
        container_name: php-app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8304:8304
networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
